version: '3'
services:
  server:
    build:
      context: ./adventure-atlas-backend
      dockerfile: Dockerfile
    container_name: server
    ports:
      - 8080:8080

  ui:
    build:
      context: ./adventure-atlas-frontend
      dockerfile: Dockerfile
    container_name: ui
    ports:
      - 4200:80
    links:
      - server